### ISSUE TITLE
gui-tool run fails with CTRL+C in ubuntu

### ISSUE THREAD

**Issue by vartomi** [vartomi/gui-tool#3]
[ERR] node server.js development /home/vartomi/gt/webui without-log
Error: Command failed: 
    at ChildProcess.exithandler (child_process.js:658:15)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Socket.<anonymous> (child_process.js:979:11)
    at Socket.emit (events.js:95:17)
    at Pipe.close (net.js:466:12)
[INF] Child processes will be closed

**Comment by vartomi** [comment]
Fixed
